- name: CuteBOT
  if: steps.check_for_atul.outputs.atul_found == 'true'
  run: |
    COMMENT="Heyyyy, are you free this evening?"
    echo "$COMMENT"
    GITHUB_TOKEN=$GITHUB_TOKEN gh pr comment ${{ github.event.number }} --body "$COMMENT"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
