name: CuteBOT

on:
  push:
    branches:
      - main  # Modify based on your main branch name
  pull_request:
    branches:
      - main  # Modify based on your main branch name

jobs:
  comment_on_atul:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check for "atul" in commit messages
      run: |
        git diff-tree --no-commit-id --name-only -r ${{ github.event.after }} | grep -q "atul"
        ATUL_FOUND=$?
        if [ $ATUL_FOUND -eq 0 ]; then
          echo "Found 'Atul' in commit changes."
          echo "::set-output name=atul_found::true"
        else
          echo "No 'Atul' found in commit changes."
          echo "::set-output name=atul_found::false"
        fi
        
    - name: Comment something funny if "Atul" found
      if: steps.check_for_atul.outputs.atul_found == 'true'
      run: |
        COMMENT="Hey @${{ github.event.pull_request.user.login }} looks like you mentioned 'Atul'"
        echo "$COMMENT"
        GITHUB_TOKEN=$GITHUB_TOKEN gh pr comment ${{ github.event.number }} --body "$COMMENT"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}