name: Test Bot
on:
  pull_request:
    types:
      - opened

jobs:
  comment_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Hello
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: 'Hello'
            });
