name: PR Commenter

on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="This PR will be addressed shortly."
          echo "$COMMENT"
          GITHUB_TOKEN=$GITHUB_TOKEN gh pr comment ${{ github.event.number }} --body "$COMMENT"